# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: playplay.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'playplay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eplayplay.proto\x12\x15votify.playplay.proto\"\xd4\x01\n\x16PlayPlayLicenseRequest\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\r\n\x05token\x18\x02 \x01(\x0c\x12\x10\n\x08\x63\x61\x63he_id\x18\x03 \x01(\x0c\x12;\n\rinteractivity\x18\x04 \x01(\x0e\x32$.votify.playplay.proto.Interactivity\x12\x38\n\x0c\x63ontent_type\x18\x05 \x01(\x0e\x32\".votify.playplay.proto.ContentType\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\"1\n\x17PlayPlayLicenseResponse\x12\x16\n\x0eobfuscated_key\x18\x01 \x01(\x0c*I\n\rInteractivity\x12\x19\n\x15UNKNOWN_INTERACTIVITY\x10\x00\x12\x0f\n\x0bINTERACTIVE\x10\x01\x12\x0c\n\x08\x44OWNLOAD\x10\x02*Z\n\x0b\x43ontentType\x12\x18\n\x14UNKNOWN_CONTENT_TYPE\x10\x00\x12\x0f\n\x0b\x41UDIO_TRACK\x10\x01\x12\x11\n\rAUDIO_EPISODE\x10\x02\x12\r\n\tAUDIO_ADD\x10\x03\x42\x19H\x02\xaa\x02\x14\x45um.Spotify.playplay')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'playplay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\002\252\002\024Eum.Spotify.playplay'
  _globals['_INTERACTIVITY']._serialized_start=307
  _globals['_INTERACTIVITY']._serialized_end=380
  _globals['_CONTENTTYPE']._serialized_start=382
  _globals['_CONTENTTYPE']._serialized_end=472
  _globals['_PLAYPLAYLICENSEREQUEST']._serialized_start=42
  _globals['_PLAYPLAYLICENSEREQUEST']._serialized_end=254
  _globals['_PLAYPLAYLICENSERESPONSE']._serialized_start=256
  _globals['_PLAYPLAYLICENSERESPONSE']._serialized_end=305
# @@protoc_insertion_point(module_scope)
